language: python
env:
  global:
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  - CONDA_DEPENDENCIES='sphinx pillow coveralls coverage codecov trollimage aggdraw
    pytest pytest-cov'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
  - CONDA_CHANNEL_PRIORITY='strict'
matrix:
  include:
  - env: PYTHON_VERSION=3.8
    os: linux
    language: generic
  - env: PYTHON_VERSION=3.7
    os: linux
    language: generic
  - env: PYTHON_VERSION=3.8
    os: osx
    language: generic
  - env: PYTHON_VERSION=3.8
    os: linux
    language: generic
    arch: ppc64le
  - env: PYTHON_VERSION=3.7
    os: linux
    arch: ppc64le
    language: generic
install:
 - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
       wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-4.7.11-linux-ppc64le.exe -O conda.exe;
       chmod +x conda.exe;
       export CONDA_ALWAYS_YES=1;
       ./conda.exe create -p $HOME/miniconda python=$TRAVIS_PYTHON_VERSION conda pytest pytest-cov ;
       export PATH="$HOME/miniconda/bin:$PATH";
       hash -r;
       pip install Pillow;
       pip install numpy;
       pip install trollimage;
       pip install aggdraw;
       pip install --no-deps -e .;
   else
       git clone --depth 1 git://github.com/astropy/ci-helpers.git;
       source ci-helpers/travis/setup_conda.sh;
       pip install --no-deps -e .;
   fi
script:
- pytest --cov=pydecorate test.py
after_success:
- if [[ $PYTHON_VERSION == 3.8 ]]; then coveralls; codecov; fi
deploy:
  - provider: pypi
    user: dhoese
    password:
      secure: PoMrJlgTJRzDvqDRs5H/k/1nkqada+zfiUTUXZEvulebkAVCu3Sj945fNQVsgq3Ha0hlyttuNGyJbLf8KUZIX9y9OJr3TuP253hQx+Ghe6scH5SFHrSj6s4ROinc9HeZfwzGlObZoeV042aSgf77O/ocGUiA54f2ZLYa8U15w9A=
    distributions: sdist
    skip_existing: true
    on:
      tags: true
      repo: pytroll/pydecorate
